"""empty message

Revision ID: 72823c3289a5
Revises: 9f18e77530eb
Create Date: 2026-04-06 22:42:40.660146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72823c3289a5'
down_revision = '9f18e77530eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('hair_color')
        batch_op.drop_column('eye_color')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
